version: '3.9'

services:
  fastapi-app:
    build: .
    container_name: fastapi-container
    ports:
      - "8000:80"
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=peliculas
      - DB_USER=postgres
      - DB_PASSWORD=secret
      - PYTHONPATH=/app
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: peliculas
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
